# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/framework-gpt',
                'doc_host': 'https://batterylake.github.io',
                'git_url': 'https://github.com/batterylake/framework-gpt',
                'lib_path': 'framework_gpt'},
  'syms': { 'framework_gpt.bigram': { 'framework_gpt.bigram.BigramLanguageModel': ( 'bigram.html#bigramlanguagemodel',
                                                                                    'framework_gpt/bigram.py'),
                                      'framework_gpt.bigram.BigramLanguageModel.__init__': ( 'bigram.html#bigramlanguagemodel.__init__',
                                                                                             'framework_gpt/bigram.py'),
                                      'framework_gpt.bigram.BigramLanguageModel.forward': ( 'bigram.html#bigramlanguagemodel.forward',
                                                                                            'framework_gpt/bigram.py'),
                                      'framework_gpt.bigram.BigramLanguageModel.generate': ( 'bigram.html#bigramlanguagemodel.generate',
                                                                                             'framework_gpt/bigram.py'),
                                      'framework_gpt.bigram.get_batch': ('bigram.html#get_batch', 'framework_gpt/bigram.py')},
            'framework_gpt.prepare': {}}}
