# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/framework-gpt',
                'doc_host': 'https://batterylake.github.io',
                'git_url': 'https://github.com/batterylake/framework-gpt',
                'lib_path': 'framework_gpt'},
  'syms': {'framework_gpt.core': {'framework_gpt.core.foo': ('core.html#foo', 'framework_gpt/core.py')}}}
