# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_prepare.ipynb.

# %% auto 0
__all__ = ['chars', 'vocab_size', 'stoi', 'itos', 'encode', 'decode']

# %% ../nbs/00_prepare.ipynb 5
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# %% ../nbs/00_prepare.ipynb 9
chars = sorted(list(set(text)))
vocab_size = len(chars)

# %% ../nbs/00_prepare.ipynb 12
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s] #encoder: string -> list of integers
decode = lambda l: ''.join(itos[i] for i in l) #decoder: list of integers -> string
